"""Add onboarding_completed_at field for Phase 3

Revision ID: 1723fabe8f8c
Revises: 8b8ce54544c9
Create Date: 2025-09-30 15:18:01.169285

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1723fabe8f8c'
down_revision: str | Sequence[str] | None = '8b8ce54544c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    # ### end Alembic commands ###
